name: Update Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (without v prefix, e.g. 0.25.0)'
        required: true
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      token:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout homebrew-oxen repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HOMEBREW_DEPLOY_PAT }}
          repository: oxen-ai/homebrew-oxen

      - name: Set version
        id: version
        run: |
          # Remove 'v' prefix if it exists
          VERSION="${{ inputs.version }}"
          VERSION="${VERSION#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Make scripts executable
        run: |
          chmod +x update_formula.sh
          chmod +x compute_hashes.sh

      - name: Update formula
        run: ./update_formula.sh ${{ env.VERSION }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_DEPLOY_PAT }} 
          commit-message: "chore: update formula to version ${{ env.VERSION }}"
          title: "Update formula to version ${{ env.VERSION }}"
          body: |
            Updates the Homebrew formula to version ${{ env.VERSION }}
            
            This PR was automatically created by GitHub Actions.
          branch: update-formula-${{ env.VERSION }}
          delete-branch: true
          base: main